# This is a basic workflow to help you get started with Actions
name: Update KAPLAYGROUND version

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  updateallrepos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'kaplayjs',
              repo: 'kaplayground',
              workflow_id: 'upgrade-submodules.yml',
              ref: 'dev'
            })